# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages: Thinkr-open/golem

addons:
  apt:
    packages:
      - libv8-3.14-dev
      - libudunits2-dev
